### PR TITLE
wieckiewicz.org

### PR DESCRIPTION
**Pull request by idarek**
May I know why your blocking filter contains my website `https://dariusz.wieckiewicz.org/en/`.

There are no ads, popup or shady practices on my website hence I am very interested in what caused that.

Please remove my website from your filter.

### CODE REVIEW

**Review by bogachenko — APPROVED** [review]

**Comment by idarek** [comment]
Thank you.

**Comment by bogachenko** [comment]
When I added your site there was an anti-block, that's why it is on my list.

In addition to my list, he was also in [uBO](https://github.com/uBlockOrigin/uAssets/issues/4368#issuecomment-628801969).

**Comment by idarek** [comment]
As I discovered with others who got it on their list it was based on 2019 data. A lot of change since 2019.

ps. `dariusz.wieckiewicz.org` still showing on the list despite margin/pulling. Possibly was in more than one place?

**Comment by bogachenko** [comment]
I do not argue, the data is old, but still this code was there.

Thanks for your help :)

**Pull request merged**
